config/routes.rb
Rails.application.routes.draw do
  # Signed in homepage
  root to: 'pieces#index'

  get 'signup',  to: 'users#new',        as: 'signup'
  get 'signin',  to: 'sessions#new',     as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :tags, only: [:index, :show]
  resources :wishlists
  resources :users
  resources :outfits
  resources :sessions

  resources :pieces, except: [:index] do
    member do
      delete "delete_image/:image_id", action: :delete_image, as: 'delete_image'
    end
  end

  get 'pieces', to: redirect('/')

  resources :outfits do
    member do
      delete "delete_image/:image_id", action: :delete_image, as: 'delete_image'
    end
  end
end

app/models/outfit.rb
class Outfit < ApplicationRecord
  belongs_to :user

  has_many :stylings, dependent: :destroy
  has_many :pieces, through: :stylings
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  has_many_attached :images

  scope :list_order, -> { order(created_at: :desc) }
  scope :by, ->(user) { where(user_id: user.id) }
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :authorize
  before_action :set_outfit, only: [:show, :edit, :update, :destroy]

  def index
    @outfits = current_user.outfits.list_order
  end

  def show
  end

  def new
    @outfit = Outfit.new
    @pieces = current_user.pieces
  end

  def edit
    @pieces = current_user.pieces
  end

  def create
    tags = params[:tags]
    @outfit = current_user.outfits.new(outfit_params)

    if @outfit.save
      tags.downcase.split(',').each do |tag_name|
        tag = Tag.find_or_create_by(name: tag_name.strip)
        @outfit.taggings.create(user_id: current_user.id, tag_id: tag.id)
      end

      redirect_to @outfit, notice: 'Outfit was successfully created.'
    else
      render :new
    end
  end

  # TODO make tagging on update and create more idiomatic
  def update
    tags = params[:tags]
    @outfit.taggings.destroy_all

    tags.downcase.split(',').each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name.strip)
      @outfit.taggings.create(user_id: current_user.id, tag_id: tag.id)
    end

    if @outfit.update(outfit_params)
      redirect_to @outfit, notice: 'Outfit was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @outfit.destroy
    redirect_to outfits_url, notice: 'Outfit was successfully destroyed.'
  end

  def delete_image
    attachment = ActiveStorage::Attachment.find(params[:image_id])
    attachment.purge
    redirect_back(fallback_location: new_outfit_path)
  end

  private

  def set_outfit
    @outfit = current_user.outfits.find(params[:id])
  end

  def outfit_params
    params.require(:outfit).permit(:name, :formality, :work, :tags, piece_ids: [], images: [])
  end
end

app/helpers/outfits_helper.rb
module OutfitsHelper
  def piece_check_box form:, piece:
    form.check_box :piece_ids,
                   {
                     id: "outfit_piece_ids_#{piece.id}",
                     name: 'outfit[piece_ids][]',
                     class: 'form-check-input sr-only'
                   },
                   piece.id,
                   nil
  end

  def image_tag_for item, options = {}
    if item.images.first.present?
      url = item.images.first.variant(auto_orient: true)
    else
      url = 'https://via.placeholder.com/150'
    end
    
    image_tag url, options 
  end
end

app/views/outfits/_form.html.erb
<%= form_with(model: outfit, local: true) do |form| %>
  <% if outfit.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(outfit.errors.count, 'error') %> prohibited this outfit from being saved:</h2>

      <ul>
        <% outfit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group mb-5'>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control form-control-lg' %>
  </div>

  <div class="row">
    <div class="col-12 col-md-6">
      <div class='form-group mb-5'>
        <%= form.label :formality, 'On a scale of 1-10, how formal is this outfit?' %><br>

        <%= form.range_field :formality, class: 'range-wrapper', min: 1, max: 10, value: 5 %>
        <span class='js-formality-text h3'>5</span>

        <p class='form-text text-muted'>
          1 is the least formal. 10 is the most formal.
        </p>
      </div>
    </div>

    <div class="col-12 col-md-6">
      <div class='form-group mb-5'>
        <%= form.label :work, 'Can you wear this outfit to work?' %><br>

        <%= form.radio_button :work, true, class: 'sr-only' %>
        <%= form.label 'work_true', 'Yes' %>
        <%= form.radio_button :work, false, class: 'sr-only' %>
        <%= form.label 'work_false', 'No' %>
      </div>
    </div>
  </div>

  <div class='form-group mb-5'>
    <%= form.label :pieces, 'What pieces from your closet make up this outfit?' %><br>

    <% @pieces.in_groups_of(12).each_with_index do |group, index| %>
      <div class='row mb-3 <%= 'js-more-pieces' unless index.zero? %>'>
        <% group.each do |piece| %>

        <div class='col-3 col-md-2 col-lg-1 mb-3'>
          <% if piece.present? %>
            <%= piece_check_box form: form, piece: piece %>

            <%= form.label "piece_ids_#{piece.id}", nil, class: 'form-check-label' do %>
              <%= image_tag_for piece %>
            <% end %>
          <% end %>
        </div><!-- .col -->

        <% end %>
      </div><!-- .row -->
    <% end %>

    <% if @pieces.length > 12 %>
      <button class='js-pieces-button btn btn-outline-primary'>
        Show
        <span class='js-pieces-show-more'>more…</span>
        <span class='js-pieces-show-less' style='display: none'>less…</span>
      </button>
    <% end %>

    <% if @pieces.blank? %>
      <%= link_to 'Add some pieces to your closet first →', new_piece_path, class: 'btn btn-outline-primary' %>
    <% end %>
  </div>

  <div class='form-group mb-5'>
    <%= form.label :images, 'Add photos of you in this outfit' %><br>
    <%= form.file_field :images, multiple: true %>
  </div>


  <div class='row mb-4'>
    <% @outfit.images.in_groups_of(4).each do |group| %>
      <% group.each do |image| %>
        <div class='col-6 col-md-3'>
          <% if image.present? %>
            <%= link_to_unless_current image_tag(image, class: 'mb-3'), outfit, target: '_blank' %>

            <%# TODO: this shouldn't be a link_to / GET, make AJAX %>
            <%= link_to 'Delete image',
                        delete_image_outfit_path(image_id: image.id),
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: 'btn btn-outline-danger mb-5' %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>


  <%= render 'forms/tags_field', form: form, resource: @outfit %>

  <div class='actions my-5'>
    <%= form.submit 'Save outfit', class: 'btn btn-success btn-lg mr-3' %>
    <%= link_to 'Cancel', outfits_path %>
  </div>
<% end %>

app/views/outfits/_header.html.erb
<h1 class='font-weight-light'>
  <%= link_to_unless_current 'Outfits', outfits_path %>
</h1>

<%= link_to 'Create new outfit', new_outfit_path, class: 'btn btn-outline-primary' %>

<hr>

app/views/outfits/edit.html.erb
<h1 class='font-weight-light'>
  Editing outfit:
  <%= link_to @outfit.name, @outfit %>
</h1>

<hr>

<%= render 'form', outfit: @outfit %>

<div class='row'>
  <div id='danger-zone' class='offset-md-6 col-12 col-md-6'>
    <div class='card border-danger my-5'>
      <div class='card-header bg-danger text-white'>The Danger Zone</div>

      <div class='card-body text-danger'>
        <h5 class='card-title'>Delete this outfit?</h5>

        <p class='card-text'>
          If you click on this button, your outfit will be immediately deleted.
          <b>THERE IS NO UNDO.</b>
        </p>

        <%= link_to 'Delete', @outfit, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/outfits/index.html.erb
<%= render 'header' %>

<% @outfits.in_groups_of(4).each do |group| %>
  <div class='row mb-5'>
    <% group.each do |outfit| %>
      <div class='col-12 col-md-3'>
        <% if outfit.present? %>
          <%= link_to image_tag_for(outfit, class: 'mb-3'), outfit %>
        <% end %>
      </div><!-- .col -->
    <% end %>
  </div><!-- .row -->
<% end %>

app/views/outfits/new.html.erb
<h1 class='font-weight-light'>Create a new outfit from your closet</h1>

<%= render 'form', outfit: @outfit %>

app/views/outfits/show.html.erb
<%= render 'header' %>

<div class='row'>
  <div class='col-12 col-md-6'>
    <%= link_to_unless_current image_tag_for(@outfit, class: 'mb-3'), @outfit %>
  </div><!-- .col -->

  <div class='col-12 col-md-6'>
    <% if @outfit.images.length > 1 %>
      <% @outfit.images[1..-1].in_groups_of(4).each do |group| %>
        <div class='row mb-4'>
          <% group.each do |image| %>

            <div class='col-6 col-md-3'>
              <% if image.present? %>
                <%= link_to_unless_current image_tag(image), @outfit %>
              <% end %>
            </div><!-- .col -->

          <% end %>
        </div><!-- .row -->
      <% end %>
    <% end %>

    <h2 class='font-weight-light'><%= @outfit.name %></h2>

    <div class='mb-5'>
      <p>
        <span class='badge badge-light border p-2'>
          👗
          <b><%= @outfit.formality %></b><span class='text-muted font-weight-light'> / 10 formal</span>
        </span>

        <span>
          <span class='badge badge-light border p-2 font-weight-light'>
            <%= @outfit.work? ? '✅' : '🚫 Not' %>

            Work Appropriate
          </span>
        </span>
      </p>

      <% if @outfit.tags.present? %>
        <p>
          <% @outfit.tags.each do |tag| %>
            <%= link_to tag.name, tag, class: 'badge badge-secondary' %>
          <% end %>
        </p>
      <% end %>

      <p>
        <%= link_to '✏️ Edit outfit details', edit_outfit_path(@outfit), class: 'btn btn-sm btn-outline-info mb-2' %>
      </p>
    </div>

    <% if @outfit.pieces.present? %>
      <div class="card border-secondary">
        <div class="card-header">Pieces used in this outfit</div>

        <div class="card-body">
          <% @outfit.pieces.in_groups_of(4).each_with_index do |group, index| %>
            <div class="row <%= 'mb-3' unless index.zero? %>">
              <% group.each do |piece| %>

                <div class="col-3">
                  <% if piece.present? %>
                    <%= link_to image_tag_for(piece), piece %>
                  <% end %>
                </div><!-- .col -->

              <% end %>
            </div><!-- .row -->
          <% end %>
        </div><!-- .card-body -->
      </div><!-- .card-header -->
    <% end %>

  </div><!-- .col -->
</div><!-- .row -->