config/routes.rb
Rails.application.routes.draw do
  # Signed in homepage
  root to: 'pieces#index'

  get 'signup',  to: 'users#new',        as: 'signup'
  get 'signin',  to: 'sessions#new',     as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :tags, only: [:index, :show]
  resources :wishlists
  resources :users
  resources :outfits
  resources :sessions

  resources :pieces, except: [:index] do
    member do
      delete "delete_image/:image_id", action: :delete_image, as: 'delete_image'
    end
  end

  get 'pieces', to: redirect('/')

  resources :outfits do
    member do
      delete "delete_image/:image_id", action: :delete_image, as: 'delete_image'
    end
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user

  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authorize
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]


  def index
    @wishlists = current_user.wishlists
  end

  def show
  end

  def new
    @wishlist = Wishlist.new
  end

  def edit
  end

  def create
    @wishlist = current_user.wishlists.new(wishlist_params)

    if @wishlist.save
      redirect_to @wishlist, notice: 'Wishlist was successfully created.'
    else
      render :new
    end
  end

  def update
    if @wishlist.update(wishlist_params)
      redirect_to @wishlist, notice: 'Wishlist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @wishlist.destroy
    redirect_to wishlists_url, notice: 'Wishlist was successfully destroyed.'
  end

  private

  def set_wishlist
    @wishlist = Wishlist.find(params[:id])
  end

  def wishlist_params
    params.require(:wishlist).permit(:url, :notes, :product_url)
  end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_with(model: wishlist, local: true) do |form| %>
  <% if wishlist.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(wishlist.errors.count, 'error') %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% wishlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= form.label :url, 'Image URL' %>
    <%= form.url_field :url, class: 'form-control form-control-lg', autofocus: true %>

    <p class='form-text text-muted'>
      Copy and paste an image URL here
    </p>
  </div>

  <div class='form-group'>
    <%= form.label :product_url, 'Product URL' %>
    <%= form.url_field :product_url, class: 'form-control form-control-lg' %>

    <p class='form-text text-muted'>
      Copy and paste a item URL here
    </p>
  </div>

  <div class='form-group'>
    <%= form.label :notes %>
    <%= form.text_area :notes, class: 'form-control form-control-lg', rows: 10 %>
  </div>

  <div class='actions mt-5'>
    <%= form.submit 'Save wishlist item', class: 'btn btn-success btn-lg mr-3'%>
    <%= link_to 'Cancel', wishlists_path %>
  </div>
<% end %>

app/views/wishlists/_header.html.erb
<h1 class='font-weight-light'>
  <%= link_to_unless_current 'Wishlist', wishlists_path %>
</h1>

<%= link_to 'Create new wishlist item', new_wishlist_path, class: 'btn btn-outline-primary' %>

<hr>

app/views/wishlists/_wishlist.html.erb
<div class='row mb-5'>
  <div class='col-12 col-md-6'>
    <% if wishlist.url.present? %>
      <div class='mb-3'>
        <%= link_to_unless_current(image_tag(wishlist.url), wishlist) %>
      </div>
    <% end %>
  </div><!-- .col -->

  <div class='col-12 col-md-6'>
    <p>
      <%= link_to "Go to item web page →", wishlist.product_url, class: 'btn btn-outline-primary', target: :blank %>
    </p>

    <div>
      <%= auto_link(simple_format(wishlist.notes), :all, target: :blank) %>
    </div>

    <div>
      <% wishlist.tags.each do |tag| %>
        <%= tag.name %>
      <% end %>
    </div>

    <%= link_to '✏️ Edit item details', edit_wishlist_path(wishlist), class: 'btn btn-sm btn-outline-info' %>
    <%= link_to '👀 View item details', wishlist, class: 'btn btn-sm btn-outline-info' if action_name == 'index' %>
  </div><!-- .col -->
</div><!-- .row -->

app/views/wishlists/edit.html.erb
<h1 class='font-weight-light'>
  Edit wishlist item details
</h1>

<%= render 'form', wishlist: @wishlist %>

<div class='row'>
  <div id='danger-zone' class='offset-md-6 col-12 col-md-6'>
    <div class='card border-danger my-5'>
      <div class='card-header bg-danger text-white'>The Danger Zone</div>

      <div class='card-body text-danger'>
        <h5 class='card-title'>Delete this item from your wishlist?</h5>

        <p class='card-text'>
          If you click on this button, your wishlist item will be immediately deleted.
          <b>THERE IS NO UNDO.</b>
        </p>

        <%= link_to 'Delete', @wishlist, method: :delete, data: { confirm: 'Are you sure you’re sure?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/wishlists/index.html.erb
<%= render 'header' %>

<%= render @wishlists %>

app/views/wishlists/new.html.erb
<h1 class='font-weight-light'>
  Add a new item to your wishlist
</h1>

<%= render 'form', wishlist: @wishlist %>

app/views/wishlists/show.html.erb
<%= render 'header' %>

<%= render @wishlist %>