config/routes.rb
Rails.application.routes.draw do
  # Signed in homepage
  root to: 'pieces#index'

  get 'signup',  to: 'users#new',        as: 'signup'
  get 'signin',  to: 'sessions#new',     as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :tags, only: [:index, :show]
  resources :wishlists
  resources :users
  resources :outfits
  resources :sessions

  resources :pieces, except: [:index] do
    member do
      delete "delete_image/:image_id", action: :delete_image, as: 'delete_image'
    end
  end

  get 'pieces', to: redirect('/')

  resources :outfits do
    member do
      delete "delete_image/:image_id", action: :delete_image, as: 'delete_image'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/outfit.rb
class Outfit < ApplicationRecord
  belongs_to :user

  has_many :stylings, dependent: :destroy
  has_many :pieces, through: :stylings
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  has_many_attached :images

  scope :list_order, -> { order(created_at: :desc) }
  scope :by, ->(user) { where(user_id: user.id) }
end

app/models/piece.rb
class Piece < ApplicationRecord
  belongs_to :user

  has_many :stylings, dependent: :destroy
  has_many :outfits, through: :stylings
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  has_many_attached :images

  scope :list_order, -> { order(created_at: :desc) }
  scope :by, ->(user) { where(user_id: user.id) }
end

app/models/styling.rb
class Styling < ApplicationRecord
  belongs_to :piece
  belongs_to :outfit
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :outfits, through: :taggings, source: :taggable, source_type: "Outfit"
  has_many :pieces, through: :taggings, source: :taggable, source_type: "Piece"
  has_many :wishlists, through: :taggings, source: :taggable, source_type: "Wishlist"

  validates :name, presence: true, uniqueness: true

  def outfits_by(user)
    outfits.by(user)
  end

  def pieces_by(user)
    pieces.by(user)
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :taggable, polymorphic: true, touch: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :email, presence: true, uniqueness: true
  validates :user_name, presence: true, uniqueness: true

  has_many :outfits
  has_many :pieces
  has_many :wishlists

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user

  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :authorize
  before_action :set_outfit, only: [:show, :edit, :update, :destroy]

  def index
    @outfits = current_user.outfits.list_order
  end

  def show
  end

  def new
    @outfit = Outfit.new
    @pieces = current_user.pieces
  end

  def edit
    @pieces = current_user.pieces
  end

  def create
    tags = params[:tags]
    @outfit = current_user.outfits.new(outfit_params)

    if @outfit.save
      tags.downcase.split(',').each do |tag_name|
        tag = Tag.find_or_create_by(name: tag_name.strip)
        @outfit.taggings.create(user_id: current_user.id, tag_id: tag.id)
      end

      redirect_to @outfit, notice: 'Outfit was successfully created.'
    else
      render :new
    end
  end

  # TODO make tagging on update and create more idiomatic
  def update
    tags = params[:tags]
    @outfit.taggings.destroy_all

    tags.downcase.split(',').each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name.strip)
      @outfit.taggings.create(user_id: current_user.id, tag_id: tag.id)
    end

    if @outfit.update(outfit_params)
      redirect_to @outfit, notice: 'Outfit was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @outfit.destroy
    redirect_to outfits_url, notice: 'Outfit was successfully destroyed.'
  end

  def delete_image
    attachment = ActiveStorage::Attachment.find(params[:image_id])
    attachment.purge
    redirect_back(fallback_location: new_outfit_path)
  end

  private

  def set_outfit
    @outfit = current_user.outfits.find(params[:id])
  end

  def outfit_params
    params.require(:outfit).permit(:name, :formality, :work, :tags, piece_ids: [], images: [])
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :authorize
  before_action :set_piece, only: [:show, :edit, :update, :destroy]

  def index
    @pieces = current_user.pieces.list_order
  end

  def show
  end

  def new
    @piece = Piece.new
  end

  def edit
  end

  def create
    tags = params[:tags]
    @piece = current_user.pieces.new(piece_params)

    if @piece.save
      tags.downcase.split(',').each do |tag_name|
        tag = Tag.find_or_create_by(name: tag_name.strip)
        @piece.taggings.create(user_id: current_user.id, tag_id: tag.id)
      end
      redirect_to @piece, notice: 'Piece was successfully created.'
    else
      render :new
    end
  end

  # TODO make tagging on update and create more idiomatic
  def update

    tags = params[:tags]
    @piece.taggings.destroy_all

    tags.downcase.split(',').each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name.strip)
      @piece.taggings.create(user_id: current_user.id, tag_id: tag.id)
    end

    if @piece.update(piece_params)
      redirect_to @piece, notice: 'Piece was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @piece.destroy
    redirect_to pieces_url, notice: 'Piece was successfully destroyed.'
  end

  def delete_image
    attachment = ActiveStorage::Attachment.find(params[:image_id])
    attachment.purge
    redirect_back(fallback_location: new_piece_path)
  end

  private

  def set_piece
    @piece = current_user.pieces.find(params[:id])
  end

  def piece_params
    params.require(:piece).permit(:name, :tags, images: [])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = current_user.tags.uniq.sort_by { |tag| tag.name.downcase }
  end

  def show
    @tag = Tag.find(params[:id])
    outfits = @tag.outfits_by(current_user)
    pieces = @tag.pieces_by(current_user)

    @items = []
    [outfits, pieces].flatten.each do |item|
      item.images.each do |image|
        @items << [image, item]
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sign_in_or_sign_up
    if on_sign_in_page?
      'Sign in'
    else
      'Sign up'
    end 
  end

  def on_sign_in_page?
    controller_name == 'sessions'
  end
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
  def piece_check_box form:, piece:
    form.check_box :piece_ids,
                   {
                     id: "outfit_piece_ids_#{piece.id}",
                     name: 'outfit[piece_ids][]',
                     class: 'form-check-input sr-only'
                   },
                   piece.id,
                   nil
  end

  def image_tag_for item, options = {}
    if item.images.first.present?
      url = item.images.first.variant(auto_orient: true)
    else
      url = 'https://via.placeholder.com/150'
    end
    
    image_tag url, options 
  end
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/app_description/_homepage.html.erb
<h2 class="row justify-content-md-center mt-5 mb-3">
  <%= sign_in_or_sign_up %>
  and use DressMe today
</h2>

<div class="row justify-content-md-center mt-5 mb-3">
 <ul class="col-12 col-md-6 list-unstyled">
    <li>Upload images and descriptions of each piece in your wardrobe. </li>
    <li>Create and save outfit combos you love. </li> 
    <li>Add items you want to your wishlist. </li> 
  </ul>
</div>

app/views/closet/index.html.erb
<% if current_user %>
  <p>
    Welcome, <%= current_user.user_name %>.<br>
    <%= link_to "Let’s find the perfect outfit for you", new_piece_path %>
  </p>

    <div class='row mb-5'>
      <% @items.in_groups_of(4).each do |group| %>
        <% group.each do |item| %>
          <div class='col-12 col-md-3'>
            <% if item.present? %>
              <%= link_to image_tag_for(item), item %>
            <% end %>
          </div> <!--.col-->
        <% end %>
      <% end %>
    </div><!--.row-->

<% else %>

  <div class="my-5 text-center">
    <h1><%= link_to_unless_current "DressMe", root_path %></h1>
    <%= link_to "Sign Up", signup_path, class: "btn btn-primary" %>
    <%= link_to "Sign In", signin_path, class: "btn btn-primary" %>
  </div>

<% end %>

app/views/dashboard/index.html.erb
<% if current_user %>
  <p>
    Welcome, <%= current_user.user_name %>.<br>
    Let’s find the perfect outfit for you.
  </p>

  <h1>Closet</h1>

  <% @items.each do |item| %>
    <% if item.images.attached? %>
      <%= link_to image_tag(url_for item.images.first), item %>
    <% end %>
  <% end %>

<% else %>

  <div class="my-5 text-center">
    <h1><%= link_to_unless_current "DressMe", root_path %></h1>
    <%= link_to "Sign Up", signup_path, class: "btn btn-primary" %>
    <%= link_to "Sign In", signin_path, class: "btn btn-primary" %>
  </div>

<% end %>

app/views/forms/_tags_field.html.erb
<div class='form-group mb-4'>
  <%= form.label :tags %><br>
  <%= text_field_tag :tags, resource.tags.map {|tag| tag.name }.join(', '), class: 'form-control form-control-lg' %>

  <p class='form-text text-muted'>
    Comma separated. Example: <code>black, ball gown, shiny</code>
  </p>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <div class="container">
    <% if !current_user %>
      <b>DressMe</b>
        <% unless on_sign_in_page? %>
        <p class="mt-3">
          Already have an account?
          <%= link_to 'Sign in here', signin_path %>
        </p>
      <% end %>    
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% if current_user %>

      <b><%= link_to "Closet", root_path %></b>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Pieces", pieces_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Outfits", outfits_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Wishlist", wishlists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Tags', tags_path, class: "nav-link" %>
          </li>
        </ul>
      </div>

    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DressMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render "layouts/nav" %>

    <main class="container mb-5">
      <% if alert.present? %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <% if notice.present? %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <footer class="text-center my-5 container">
      <ul class="navbar-nav text-muted">
        <li>
          © 2018–<%= Time.now.year %>
        </li>

        <% if current_user %>
          <li>
            <%= link_to "Sign Out", signout_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </footer>
  </body>
</html>

app/views/photos/index.html.erb
<% if current_user %>
  <p>
    Welcome, <%= current_user.user_name %>.<br>
    Let’s find the perfect outfit for you.
  </p>

  <h1>Closet</h1>

  <% @photos.each do |photo| %>
    <% if photo.images.attached? %>
      <%= link_to image_tag(url_for photo.images.first), photo %>
    <% end %>
  <% end %>

<% else %>

  <div class="my-5 text-center">
    <h1><%= link_to_unless_current "DressMe", root_path %></h1>
    <%= link_to "Sign Up", signup_path, class: "btn btn-primary" %>
    <%= link_to "Sign In", signin_path, class: "btn btn-primary" %>
  </div>

<% end %>